"""Reproduction package exporter for findings.

Creates operator-friendly artifacts from structured findings:
- reproduction.json: machine-readable steps and HTTP evidence
- reproduce.sh: curl commands for findings that have captured HTTP requests
"""
from __future__ import annotations

import json
import shlex
from pathlib import Path

from .request_logger import _redact_headers
from .scanners.base import Finding


def write_reproduction_package(findings: list[Finding], output_dir: Path) -> dict:
    items = [_finding_to_repro_item(f, i + 1) for i, f in enumerate(findings)]
    json_path = output_dir / "reproduction.json"
    shell_path = output_dir / "reproduce.sh"

    json_path.write_text(json.dumps({"findings": items}, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by WScan. Review targets and payloads before running.",
        "",
    ]
    for item in items:
        curl = item.get("curl_command", "")
        if not curl:
            continue
        lines.extend([
            f"echo {shlex.quote('[%03d] %s %s' % (item['id'], item['check_type'], item['field_name']))}",
            curl,
            "",
        ])
    shell_path.write_text("\n".join(lines), encoding="utf-8")
    try:
        shell_path.chmod(0o755)
    except Exception:
        pass

    return {"json": str(json_path), "shell": str(shell_path), "count": len(items)}


def _finding_to_repro_item(finding: Finding, item_id: int) -> dict:
    request = dict(finding.request or {})
    if "headers" in request:
        request["headers"] = _redact_headers(request["headers"])
    response = {k: v for k, v in (finding.response or {}).items() if k != "body"}
    if "headers" in response:
        response["headers"] = _redact_headers(response["headers"])

    return {
        "id": item_id,
        "check_type": finding.check_type,
        "severity": finding.severity,
        "confidence": finding.confidence,
        "verified": finding.verified,
        "url": finding.url,
        "field_name": finding.field_name,
        "payload": finding.payload,
        "evidence": finding.evidence,
        "evidence_type": finding.evidence_type,
        "evidence_details": finding.evidence_details,
        "reproduction_steps": finding.reproduction_steps,
        "request": request,
        "response": response,
        "curl_command": _curl_from_request(finding.request or {}),
    }


def _curl_from_request(request: dict) -> str:
    url = request.get("url") or ""
    if not url:
        return ""
    method = (request.get("method") or "GET").upper()
    headers = request.get("headers") or {}
    body = request.get("post_data") or ""

    parts = ["curl", "-i", "-sS", "-X", shlex.quote(method)]
    skip_headers = {"host", "content-length", "connection", "accept-encoding"}
    # 認証ヘッダの値は成果物へ平文で残さない（curl はテンプレートとして提示し、
    # 実行時にトークンを差し替える前提）。ヘッダ名は再現の手掛かりとして残す。
    from .request_logger import _SENSITIVE_HEADERS
    for key, value in headers.items():
        if key.lower() in skip_headers:
            continue
        if key.lower().startswith(":"):
            continue
        if key.lower() in _SENSITIVE_HEADERS:
            value = "<REDACTED: トークンを差し替えて実行>"
        parts.extend(["-H", shlex.quote(f"{key}: {value}")])
    if body:
        parts.extend(["--data-raw", shlex.quote(body)])
    parts.append(shlex.quote(url))
    return " ".join(parts)
