"""Reproduction package exporter for findings.

Creates operator-friendly artifacts from structured findings:
- reproduction.json: machine-readable steps and HTTP evidence
- reproduce.sh: curl commands for findings that have captured HTTP requests
"""
from __future__ import annotations

import json
import shlex
from pathlib import Path

from .request_logger import _is_sensitive_header, _redact_headers
from .scanners.base import Finding


def write_reproduction_package(
    findings: list[Finding], output_dir: Path, *, authenticated: bool = False
) -> dict:
    items = [
        _finding_to_repro_item(f, i + 1, authenticated=authenticated)
        for i, f in enumerate(findings)
    ]
    json_path = output_dir / "reproduction.json"
    shell_path = output_dir / "reproduce.sh"

    json_path.write_text(json.dumps({"findings": items}, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by WScan. Review targets and payloads before running.",
        "",
    ]
    for item in items:
        curl = item.get("curl_command", "")
        if not curl:
            continue
        lines.extend([
            f"echo {shlex.quote('[%03d] %s %s' % (item['id'], item['check_type'], item['field_name']))}",
            curl,
            "",
        ])
    shell_path.write_text("\n".join(lines), encoding="utf-8")
    try:
        shell_path.chmod(0o755)
    except Exception:
        pass

    return {"json": str(json_path), "shell": str(shell_path), "count": len(items)}


def _finding_to_repro_item(finding: Finding, item_id: int, *, authenticated: bool = False) -> dict:
    request = dict(finding.request or {})
    if "headers" in request:
        request["headers"] = _redact_headers(request["headers"])
    response = {k: v for k, v in (finding.response or {}).items() if k != "body"}
    if "headers" in response:
        response["headers"] = _redact_headers(response["headers"])

    curl_command = _curl_from_request(finding.request or {})
    steps = list(finding.reproduction_steps or [])
    if not steps:
        steps = _default_reproduction_steps(finding, request, bool(curl_command))
    return {
        "id": item_id,
        "check_type": finding.check_type,
        "severity": finding.severity,
        "confidence": finding.confidence,
        "verified": finding.verified,
        # boolean だけでは assumed/unreproduced/skipped（いずれも False）が潰れる。
        # 再現可否を確かめる operator 向け成果物なので state と note も出す。
        "verification_state": getattr(finding, "verification_state", ""),
        "verification_note": getattr(finding, "verification_note", ""),
        "url": finding.url,
        "field_name": finding.field_name,
        "payload": finding.payload,
        "evidence": finding.evidence,
        "evidence_type": finding.evidence_type,
        "evidence_details": finding.evidence_details,
        "preconditions": {
            # captured request ヘッダから推定するが、Agent finding は認証後でも request
            # ヘッダを持たず常に False になる（Codex #154 P2）。run が認証済み（user/pass・
            # TOTP・storage-state）なら、その run の finding は認証セッション無しでは再現不能な
            # ため authorization_required を立てる。
            "authorization_required": bool(authenticated) or any(
                _is_sensitive_header(name) for name in (request.get("headers") or {})
            ),
            "note": "Use an authorized test account and replace all redacted values at runtime.",
        },
        "reproduction_steps": steps,
        "negative_control": (
            f"Repeat the same request for {finding.field_name or 'the same input'} with a benign value "
            "and confirm the vulnerable behavior is absent."
        ),
        "expected_observation": finding.evidence or finding.evidence_type,
        "verification": {
            "state": getattr(finding, "verification_state", ""),
            "note": getattr(finding, "verification_note", ""),
        },
        "request": request,
        "response": response,
        "curl_command": curl_command,
    }


def _default_reproduction_steps(finding: Finding, request: dict, has_curl: bool) -> list[str]:
    """Agent/通常スキャンで共通利用できる最小の再現手順を補完する。"""
    steps = [f"Open the authorized target: {finding.url}"]
    if finding.field_name:
        steps.append(f"Set input {finding.field_name} to the recorded payload.")
    if has_curl:
        steps.append("Run the generated curl template after replacing redacted credentials.")
    else:
        steps.append("Submit the same form or browser action recorded by the scan.")
    steps.append("Observe the expected vulnerable behavior and capture the response evidence.")
    steps.append("Run the documented benign negative control and compare the result.")
    return steps


def _curl_from_request(request: dict) -> str:
    url = request.get("url") or ""
    if not url:
        return ""
    method = (request.get("method") or "GET").upper()
    headers = request.get("headers") or {}
    body = request.get("post_data") or ""

    parts = ["curl", "-i", "-sS", "-X", shlex.quote(method)]
    skip_headers = {"host", "content-length", "connection", "accept-encoding"}
    # 認証ヘッダの値は成果物へ平文で残さない（curl はテンプレートとして提示し、
    # 実行時にトークンを差し替える前提）。ヘッダ名は再現の手掛かりとして残す。
    for key, value in headers.items():
        if key.lower() in skip_headers:
            continue
        if key.lower().startswith(":"):
            continue
        if _is_sensitive_header(key):
            value = "<REDACTED: トークンを差し替えて実行>"
        parts.extend(["-H", shlex.quote(f"{key}: {value}")])
    if body:
        parts.extend(["--data-raw", shlex.quote(body)])
    parts.append(shlex.quote(url))
    return " ".join(parts)
